
services:
  web:
    build: .
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      JWT_SECRET: 567a4724f90aec2cf192812f7ebc22b4ac23c2c64b98c5a3859a74fa620812f3
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: